- name: copy mongodb repo file
  ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb
  ansible.builtin.yum:
     name: mongodb-org
     state: installed

- name: update moongodb listen address replace '127.0.0.1' with '0.0.0.0'
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mangodb service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes


