- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old http documents content
  ansible.builtin.file:
    name: /usr/share/nginx/html
    state: absent

- name: Create http diectory
  ansible.builtin.file:
    name: /usr/share/nginx/html
    state: directory

#- name: Download frontend content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: download {{component}} app content
  ansible.builtin.unarchive:
    src: http://{{nexus.user}}:{{nexus.pass}}@172.31.12.43:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes
  vars:
    nexus.user: "{{ lookup('aws_ssm', 'nexus.user', region='us-east-1' ) }}"
    nexus.pass: "{{ lookup('aws_ssm', 'nexus.pass', region='us-east-1' ) }}"

- name: copy roboshop conf file to nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start nginx service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes