- name: install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: load app prereq
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: build maven
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.include_tasks: "systemd.yml"