- name: install python peps
  ansible.builtin.yum:
    name:
    - python3-PyMySQL
    - mysql
    state: installed

- name: load mysql schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: mysql-dev.devops-practice.online
    login_user: root
    login_password: "{{root_mysql_password}}"
