- name: install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: load app prereq
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: download dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.3

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load